### ISSUE TITLE
No Current Version Of Kopernicus for KSP 1.4.X Available to Launch Latest Version 

### ISSUE THREAD

**Issue by GreenKeldeo** [rXenoq12/Kuikuno#1]

**Comment by rXenoq12** [comment]
Any version below 1.4 (I safely recommend 1.3.0-1.3.1) will work with the mod. If you are using steam you can go back to 1.3.1 in Properties>Betas>Select beta in the drop menu to "previous_1.3.1"

If you are not running KSP on steam then you will have to wait until a 1.4 available Kopernicus is out.

**Comment by rXenoq12** [comment]
Update to previous comment-

I will keep the version of the mod at 1.3.1 until Kopernicus comes out with a new update.
